### ISSUE TITLE
is this working?

### ISSUE THREAD

**Issue by ma7555** [atyshka/Lasernet#1]
Hello,

Is this implementation working? can you provide a ReadMe if so?

Thanks

**Comment by atyshka** [comment]
Theoretically yes, but I am still working on implementation a data input pipeline to actually train it, so it is currently unverified. I am almost finished setting up a pipeline to train on the Waymo open dataset. 

Another thing to note is that the implementation of mean shift clustering is working poorly right now, I think it may require writing a custom cuda kernel for optimal speed, so currently it is left out of the model

By the end of the month I hope to finish developing a data input pipeline and run some training in Colab, at which point I will share the jupyter notebook. Any contributions are welcome

**Comment by atyshka** [comment]
@ma7555 Happy to announce things are now working, please see readme for more info :)

**Comment by ma7555** [comment]
@atyshka great work I will check it and probably run it this week
